# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      odkfull:
        image: obolibrary/odkfull
      robot:
        image: obolibrary/robot

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Validate OBO file
      run: fastobo-validator --all pride_cv.obo

    - name: Generate OWL and validate it
      run: |
        docker pull obolibrary/robot
        # Replace the imports of the UO and PATO ontology .obo files with the equivalent .owl files
        cp pride_cv.obo tmp_pride.obo
        cp unimod.obo tmp_unimod.obo
        sed -e "s/pato.obo/pato.owl/g" -e "s/uo.obo/uo.owl/g" -i tmp_pride.obo
        sed -e "s/pato.obo/pato.owl/g" -e "s/uo.obo/uo.owl/g" -i tmp_unimod.obo
        head -n 50 tmp_pride.obo
        export JAVA_TOOL_OPTIONS=-Xmx6G
        docker run --rm -v ${{ github.workspace }}:/work obolibrary/robot robot convert -vvv -i /work/tmp_pride.obo -o /work/pride_cv.owl --format owl
        docker run --rm -v ${{ github.workspace }}:/work obolibrary/robot robot convert -vvv -i /work/tmp_unimod.obo -o /work/unimod.owl --format owl
        rm tmp_pride.obo
        rm tmp_unimod.obo
        
        # Validate the OWL file
        docker run --rm -v ${{ github.workspace }}:/work obolibrary/robot robot report --input /work/pride_cv.owl --output /work/report.tsv

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: report.tsv
        path: report.tsv
